apiVersion: apiconnect.ibm.com/v1beta1
kind: API
metadata:
  name: test-api
  namespace: cp4i
spec:
  definition:
    configMap: test-configmap
  share:
    apim:
      credentialsSecret: apim-credentials
      providerOrg: REPLACE_ME
